### PR TITLE
Update pip and centre map to web site location

### PR DESCRIPTION
**Pull request by quimnut**
2 changes for my install

woohoo

### CODE REVIEW

**Comment by quimnut** [comment]
some hardware images too

**Review by kevinelliott — CHANGES_REQUESTED** [review]
This looks great. One thing, could you update the `HARDWARE_PHOTOS` list in the `meshtastic_support.py` file with your newly added photos? This exists to tell the UI whether or not hardware has photos without needing to hit the filesystem first.

**Comment by quimnut** [comment]
Done, for the xiao_ble, that variant currently builds as private_hw but i'd expect it changes in the future.

**Review by kevinelliott — APPROVED** [review]
Fantastic, looks great! Thanks for doing that. I changed the base branch to develop to merge into and I'll merge it now and release shortly!

**Pull request merged**
