### PR TITLE
converts config to yaml

### PR DESCRIPTION
**Pull request by jshuping**
For Issue #58 , didn't realize it was already assigned until after I made the changes, whoops!

### CODE REVIEW

**Comment by kevinelliott** [comment]
@jshuping Thanks! This looks great though. The only reason I haven't merged this yet is because I'm thinking through whether or not YAML or ini would be better for being littered with comments describing the configuration.

Putting comments in YAML is easy enough, but I wonder if all the tabbing would get lost after a few paragraphs of descriptions, etc.

What are your thoughts?

**Comment by SimmerV** [comment]
I think .ini structure is slightly easier than .yaml but either is better than .json

**Comment by kevinelliott** [comment]
We chatted in the Discord about this:

just a snippet:
```
YAML
Pros:
concise
indentation makes groups/sections relatively visible
options are condensed together
Cons:
indentation hard for less technical users (oops 3 spaces instead of 2, didn't see that)
indentation less obvious once there is a lot of documentation

TOML
Pros:
familiar (at least to some who have worked with config files)
explicit sections to group like config options within
documentation feels natural here, can document a section, a subsection, and individual options without impact to a parsed layout
Cons: 
a bit more verbose
lack of visual heirarchy

From my developer perspective, JSON and YAML are the clear winners. From a user perspective (who are assumed less technical than us), I think TOML is likely the winner.
```

**Comment by kevinelliott** [comment]
Alright, we have decided to use ini.

@jshuping Would you be interested in converting this PR to using ini?

**Comment by kevinelliott** [comment]
@jshuping calling once... calling twice...

**Comment by jshuping** [comment]
HI @kevinelliott I'll let you or someone else take it on, I won't be able to help the next few weeks, but will look forward to contributing in the future!

**Pull request closed without merging**
